eb:
  base:
    file:
      local:
        dir: "/tmp/bus"
      oss:
        region: "cn-shenzhen"
        # 公网访问
        # endpoint: "https://oss-cn-shenzhen.aliyuncs.com"
        # 内网访问
        endpoint: "https://oss-cn-shenzhen-internal.aliyuncs.com"
        bucket-name: "suyh-shenzhen-public"


sys:
  web:
    user:
      captcha:
        two-factor-auth-enabled: false


---
spring:
  config:
    activate:
      on-profile: suyh,suyh_mac


eb:
  base:
    file:
      local:
        dir: "/tmp/bs"
      minio:
        endpoint: "http://minio.qu-yun.isuyh.com"
        ak: "M4HGteCOYWk43AdyKlXN"
        sk: "JZnytJbJWQGyr0u05zJsRRc3VQqCDCGN6HAn4goJ"



---
spring:
  config:
    activate:
      on-profile: suyh_dev

